name: GC_conda_env
channels:
    - conda-forge
dependencies:
    - python==3.4.2
    - opencv==3.4.2
    - jupyter==1.0.0
    - scikit-image==0.13.1
    - scipy==1.0.0
    - shapely==1.6.4
    - scikit-learn==0.19.1
    - numpy==1.18.1
    - matplotlib==3.1.2
    - glob2==0.7
